name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Compile TypeScript
        run: |
          cd src
          find . -type f -name "*.ts" -print0 | xargs -0 -I {} sed -i '1s/^/\/\/ @ts-nocheck\n/' {}
          npm install -g typescript
          tsc

      - name: Compile SASS
        run: |
          npm install -g sass
          sass src/:src/

      - name: Publish to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: src
          target-branch: gh-pages
